### ISSUE TITLE
Setting the script up

### ISSUE THREAD

**Issue by Teatimeman** [tim-smart/metabase-mailer#1]
Hi Tim,

im trying to use your script for my company, but am running into some problems. After configuring the .env i ran into the following problems: 

- Size of the PDF : ![image](https://user-images.githubusercontent.com/25906107/187457012-7a8ed6ea-486f-4ed0-ac7a-370a0d7189e6.png) This problem was solved by setting specific sizes for the PDF.
- SMTP Connection error : 

![image](https://user-images.githubusercontent.com/25906107/187458467-d0e21106-0f6b-4747-b2cb-85b0d132afd0.png) 
At this error im at a loss, i tried adding "requireTLS: true" to the constructor in email but to no avail. In the following image you can see my .env:
![image](https://user-images.githubusercontent.com/25906107/187460082-f3e1380f-23ac-4c0d-b9b9-af5e277a9e1b.png)

It would be nice if you could help or guide me in the right direction.

Best regards 

Bobby

**Comment by tim-smart** [comment]
The first issue is probably due to a older version of Metabase. What version are you running?

Second issue is due to the basic SMTP settings being used. Take a look here:
https://github.com/tim-smart/metabase-mailer/blob/master/src/email.ts#L3

At our organisation we have an internal SMTP relay in a Kubernetes cluster, which forwards it securely to our actual SMTP server.

**Comment by Teatimeman** [comment]
Thanks for the reply, so i was able to fix the connection error by adjusting the smtp settings, but the pdf only shows the login site of metabase.

**Comment by tim-smart** [comment]
Maybe give a precious version a try.

It sounds like you have an older version of metabase:
https://github.com/tim-smart/metabase-mailer/tree/0.1.12
